### ISSUE TITLE
service一問

### ISSUE THREAD

**Issue by The992255** [sky172839465/AMA_Angular#5]
使用service時，使用
```
@Component({
  ...
  providers: [AccountsService]
})
```
與不使用的差別再哪裡？

我在AccountsService裡面宣告一個物件，該物件用ngFor可以正常顯示
然而我寫一個function修改這個物件時console.log的結果也是也是修改過後的值，結果ngFor卻還是顯示修改之前的值？

html:
`<app-account *ngFor="let acc of accounts; let i = index"></app-account>`

ts:
```
export class AppComponent implements OnInit {
  accounts: {name: string, status: string}[] =[];

  constructor(private accountsService: AccountsService) {}

  ngOnInit() {
    this.accounts = this.accountsService.accounts;
  }
}
```

**Comment by sky172839465** [comment]
1. provider是把外部的服務(service)注入(inject)到你現在這個component，所以你的component才可以使用這個服務

1. 需要模擬情境用[stackblitz]模擬，你的code跟描述對不上去，沒有console.log

[stackblitz]: https://stackblitz.com/

**Comment by The992255** [comment]
https://stackblitz.com/edit/service-problem?file=src%2Fapp%2Fshow-name%2Fshow-name.component.ts
寫好了
問題在app/show-name/show-name.component.ts的第17行
`providers: [NameService]`
這邊
有加跟不加的結果差很多，點擊Add Oi就會出現問題了

**Comment by The992255** [comment]
https://stackblitz.com/edit/service-problem-2?file=src%2Fapp%2Fshow-name%2Fshow-name.component.ts
第二個，兩個檔案的差別在有沒有加入

`providers: [NameService]`

**Comment by sky172839465** [comment]
1. 前面說的你可能沒理解，service就是外面提供的服務，show-name.component.ts裡你本沒宣告過`this.nameService.addName`和`this.nameService.all_name`，為什麼你可以用?
1. providers在每個component加入的時後，就會產生一個全新的實例，所以你雖然看到show-name的console.log有多一筆，可是那是**show-name.component的nameService**裡`all_name`多了一筆，**app.component的nameService**你無全沒動到他的`all_name`
1. 這種有階層關係的時候，要共用service你必須放在他們共同之上的module上面，以現在的情況就是app.module.ts，[demo](https://stackblitz.com/edit/service-problem-replied?file=src%2Fapp%2Fapp.module.ts)
1. 看一下官方文件的說明 [英文](https://angular.io/guide/providers) [中文](https://angular.cn/guide/providers) 中文提到的實例(instance)就是上面說的產生一個全新的nameService，看完中文在去看英文

- demo連結不要一大串，用一些文字代表即可
- 不能說 [結果差很多] 這樣講沒有人知道問題在哪裡，配合你的demo應該要更清楚描述問題
- hello.component.ts 是專案產生的，沒用到就要刪除
- app.component.ts `addName`是完全沒用到的為什麼寫在那裏?
- all_name -> allName
- allName -> nameList比較容易知道他是陣列

**Comment by The992255** [comment]
那為什麼在**show-name.component**不必注入service就能使用了呢？
如果**app.component**只要刪掉`providers: [NameService]`程式就無法執行
下面說的下次會改進
