### ISSUE TITLE
rotuer之問

### ISSUE THREAD

**Issue by The992255** [sky172839465/AMA_Angular#6]
用路由導航到所需頁面的方法目前知道兩個
1.在html裡面加入`routerLink="address"`
2.在ts裡面加入`router.navigate(['address])`
這兩者有比較建議使用哪個嗎?
主要差別是什麼?
兩者並用的話程式碼似乎有點亂......

**Comment by sky172839465** [comment]
1. 不是rotuer是router，發issue前要檢查
1. 看情況使用，通常寫在html裡是先定義好，像是畫面上的選單點了要去哪裡，用js操作的通常是使用者點不到的狀況，像是你按下登入我判斷你是管理員就去後台，你是一般使用者就去自己的首頁

**Comment by The992255** [comment]
我知到了！

**Comment by sky172839465** [comment]
ok
